FROM alpine:3.17.3

RUN apk --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing add \
    php81 \
    php81-pgsql \
    php81-pdo_pgsql \
    php81-dev \
    php81-gd \
    php81-curl \
    php81-intl \
    php81-mbstring \
    php81-pcntl \
    php81-phar \
    php81-xml \
    php81-xsl \
    php81-dom \
    php81-fpm \
    php81-pecl-apcu && \
    ln -sf /usr/bin/php81 /usr/bin/php && \
    rm -rf /var/cache/apk/*

CMD ["php-fpm81", "--nodaemonize"]