version: '3.18'
services:
  nginx:
    image: nginx:alpine
    volumes: 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/php:/var/www/html
    ports: 
      - 8080:80
    networks:
      - back-end

  php:
    image: cdebray1410/3iwj-docker-project_php
    volumes:
      - ./docker/php:/var/www/html
    networks:
      - back-end

  composer:
    image: fdev4docker/3iwj-docker-project-composer-1
    volumes:
      - ./www:/var/www/html/
    command: composer --version

  adminer:
    image: cdebray1410/3iwj-docker-project_adminer
    volumes:
      - ./docker/adminer/adminer-4.8.1.php:/srv/index.php
    ports:
      - 81:80
    depends_on:
      - database
    networks:
      - back-end

  database:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 82:5432
    environment:
      POSTGRES_DB: esgi
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: Test1234
    networks:
      - back-end

volumes:
  pgdata:

networks:
  back-end:
    name: back-end