version: '3.18'
services:
  nginx:
    image: nginx:alpine
    volumes: 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/php:/var/www/html
    ports: 
      - 8080:80

  php:
    build: ./docker/php
    volumes:
      - ./docker/php:/var/www/html